language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install -g gulp
  - psql -c 'create database tipzip;' -U postgres
  - psql -U postgres -c 'create extension postgis;'
  - psql "CREATE USER df with password 'myPassword';" -U postgres
script: gulp ci